#!/usr/bin/python3
from queue import PriorityQueue
import copy

from numpy.random import rand

from which_pyqt import PYQT_VER
if PYQT_VER == 'PYQT5':
	from PyQt5.QtCore import QLineF, QPointF
else:
	raise Exception('Unsupported Version of PyQt: {}'.format(PYQT_VER))




import time
import numpy as np
from TSPClasses import *
import heapq
import itertools

SPACE_ALLOWANCE = 3
CLUSTER_SIZE = 10
MIN_CLUSTER_SIZE = 5
MAX_CLUSTER_SIZE = 20

class TSPSolver:
	def __init__( self, gui_view ):
		self._scenario = None

	def setupWithScenario( self, scenario ):
		self._scenario = scenario


	''' <summary>
		This is the entry point for the default solver
		which just finds a valid random tour.  Note this could be used to find your
		initial BSSF.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of solution, 
		time spent to find solution, number of permutations tried during search, the 
		solution found, and three null values for fields not used for this 
		algorithm</returns> 
	'''

	def defaultRandomTour( self, time_allowance=60.0 ):
		results = {}
		cities = self._scenario.getCities()
		ncities = len(cities)
		foundTour = False
		count = 0
		bssf = None
		start_time = time.time()
		while not foundTour and time.time()-start_time < time_allowance:
			# create a random permutation
			perm = np.random.permutation( ncities )
			route = []
			# Now build the route using the random permutation
			for i in range( ncities ):
				route.append( cities[ perm[i] ] )
			bssf = TSPSolution(route)
			count += 1
			if bssf.cost < np.inf:
				# Found a valid route
				foundTour = True
		end_time = time.time()
		results['cost'] = bssf.cost if foundTour else math.inf
		results['time'] = end_time - start_time
		results['count'] = count
		results['soln'] = bssf
		results['max'] = None
		results['total'] = None
		results['pruned'] = None
		return results


	''' <summary>
		This is the entry point for the greedy solver, which you must implement for 
		the group project (but it is probably a good idea to just do it for the branch-and
		bound project as a way to get your feet wet).  Note this could be used to find your
		initial BSSF.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number of solutions found, the best
		solution found, and three null values for fields not used for this 
		algorithm</returns> 
	'''

	def greedy( self,time_allowance=60.0 ):
		pass



	''' <summary>
		This is the entry point for the branch-and-bound algorithm that you will implement
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number solutions found during search (does
		not include the initial BSSF), the best solution found, and three more ints: 
		max queue size, total number of states created, and number of pruned states.</returns> 
	'''

	def branchAndBound( self, time_allowance=60.0 ):
		results = {}
		cities = self._scenario.getCities()
		max_queue = 0
		total_states = 0
		# upperBount = greedy(0)
		bssf = self.defaultRandomTour(1)['soln']
		foundTour = False
		cityMatrix = initialize_matrix(cities)
		# cityMatrix = [[item/100 for item in sub1] for sub1 in cityMatrix]
		lowerbound = reduce_cost_matrix(cityMatrix)
		start_time = time.time()
		route = []
		route.append(0)
		start_city = 0
		prioQueue = PriorityQueue()
		prioQueue_2 = PriorityQueue()
		waitQueue = PriorityQueue()
		longest_route = 0
		init_city = 0
		solution_count = 0
		pruned_states = 0
		init_state = State(route, cityMatrix, lowerbound)
		prioQueue.put((lowerbound, route, init_state))
		curr_queue_size = 0

		while time.time() - start_time < time_allowance:
			curr_queue_size = prioQueue.qsize() + prioQueue_2.qsize()
			max_queue = curr_queue_size if curr_queue_size > max_queue else max_queue
			if prioQueue.empty() and prioQueue_2.empty():
				break
			if foundTour and not prioQueue_2.empty():
				lowerbound, curr_path, curr_state = prioQueue_2.get()
			elif prioQueue.qsize() > 0:
				lowerbound, curr_path, curr_state = prioQueue.get_nowait()
			else:
				lowerbound, curr_path, curr_state = prioQueue_2.get()

			start_city = curr_path[-1]
			route = curr_state.route
			cityMatrix = curr_state.cost_matrix
			lowerbound = curr_state.lowerbound
			if lowerbound > bssf.cost:
				pruned_states += 1
				continue

			if len(route) < longest_route and not foundTour:
				prioQueue_2.put((lowerbound, route.copy(), curr_state))
				continue
			for i in range(len(cities)):
				if i != init_city:
					if cityMatrix[start_city][i] != np.inf:
						child_val, child_matrix = find_child_val(start_city, i, cityMatrix, lowerbound)
						route.append(i)
						longest_route = len(route) if len(route) > longest_route else longest_route
						child_state = State(route, child_matrix, child_val)

						if child_val > bssf.cost:
							pruned_states+=1
						else:
							waitQueue.put((child_val, route.copy(), child_state))

						total_states+=1
						route.pop()
				# print(1)

			for i in range(SPACE_ALLOWANCE):
				if waitQueue.qsize() > 0:
					if not foundTour:
						prioQueue.put(waitQueue.get())
					else:
						prioQueue_2.put(waitQueue.get())
			pruned_states += waitQueue.qsize()
			waitQueue.queue.clear()
			if len(route) == len(cities):
				curr_cost = TSPSolution([cities[idx] for idx in route])
				if curr_cost.cost == np.inf:
					route.pop()
				elif curr_cost.cost < bssf.cost:
					bssf = TSPSolution([cities[idx] for idx in route])
					foundTour = True
					print("new bssf: ", bssf.cost, "at ", time.time() - start_time)
					solution_count+=1


		end_time = time.time()

		pruned_states += curr_queue_size


		#wrap-up
		results['cost'] = bssf.cost
		results['time'] = end_time - start_time
		results['count'] = solution_count
		results['soln'] = bssf
		results['max'] = max_queue
		results['total'] = total_states
		results['pruned'] = pruned_states
		return results


	''' <summary>
		This is the entry point for the algorithm you'll write for your group project.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number of solutions found during search, the 
		best solution found.  You may use the other three field however you like.
		algorithm</returns> 
	'''

	def fancy( self,time_allowance=60.0 ):
		results = {}
		cities = self._scenario.getCities()
		# children = cluster_all_children(cities)
		cluster_prio = PriorityQueue()
		final_route = []
		final_route_2 = []
		final_route_3 = []

		time_start = time.time()
		children = Kmeans(cities)
		cluster_cost_matrix, cluster_connection_matrix = find_children_connections(children)
		##TODO: cluster route is using branch and bound, should use a greedy.
		cluster_route, pruned_states = branch_and_bound_algorithm(len(children), cluster_cost_matrix, 0)
		route_conn = select_connection_tuple(cluster_route, cluster_connection_matrix)

		for i in range(len(cluster_route)):
			child = children[cluster_route[i]]
			childMatrix = initialize_matrix(child)
			start_cluster = cluster_route[i-1]
			end_cluster = cluster_route[0] if i == len(cluster_route)-1 else cluster_route[i+1]
			start_city = route_conn[i-1][1]
			end_city = route_conn[i][0]
			if end_city not in child:
				continue
			if start_city not in child:
				continue
			start_city_idx = child.index(start_city)
			end_city_idx = child.index(end_city)
			print(i, "cluster: ", start_city._name, ", ", end_city._name)

			setup_start_and_end(childMatrix, start_city_idx, end_city_idx)
			child_route, just_pruned = branch_and_bound_algorithm(len(child), childMatrix, start_city_idx)
			pruned_states += just_pruned
			final_route_2.extend(child_route.copy())
			final_route_3.extend([child[idx]._name for idx in child_route])
			final_route.extend([child[idx] for idx in child_route])

		time_end = time.time()
		print([my_child._name for my_child in final_route])
		#wrap-up
		bssf = TSPSolution(final_route)
		results['cost'] = bssf.cost
		results['time'] = time_end - time_start
		results['count'] = 1
		results['soln'] = bssf
		results['max'] = 100
		results['total'] = 100
		results['pruned'] = pruned_states
		return results


def find_child_val(start_city_index, next_city_index, cost_matrix_orig, prev_lowerbound):
	init_cost = cost_matrix_orig[start_city_index][next_city_index]

	cost_matrix = copy.deepcopy(cost_matrix_orig)
	for i in range(len(cost_matrix[start_city_index])):
		cost_matrix[start_city_index][i] = np.inf
	for j in range(len(cost_matrix)):
		cost_matrix[j][next_city_index] = np.inf
	cost_matrix[next_city_index][start_city_index] = np.inf

	lowerbound = prev_lowerbound + reduce_cost_matrix(cost_matrix) + init_cost
	return lowerbound, cost_matrix

def reduce_cost_matrix(matrix):
	total_reduced = 0
	for i in range(len(matrix)):
		min_row = min(matrix[i])
		if min_row != 0 and min_row != np.inf:
			for j in range(len(matrix[i])):
				matrix[i][j] -= min_row
			total_reduced += min_row

	for j in range(len(matrix[0])):
		min_col = min([i[j] for i in matrix])
		if min_col != 0 and min_col != np.inf:
			for i in range(len(matrix)):
				matrix[i][j] -= min_col
			total_reduced += min_col

	return total_reduced

def initialize_matrix(cities):
	matrix = [[0 for  i in range(len(cities))] for i in range(len(cities))]
	for i in range(len(matrix)):
		for j in range(len(matrix[i])):
			matrix[i][j] = cities[i].costTo(cities[j])
	return matrix

class State:
	def __init__(self, curr_route, curr_cost_matrix, curr_lowerbound):
		self.route = copy.deepcopy(curr_route)
		self.cost_matrix = curr_cost_matrix
		self.lowerbound = curr_lowerbound



def cluster_all_children(cities):
	unused_cities = [cities[i] for i in range(len(cities))]
	cluster_list = []
	i = 0
	cluster_dict = dict()
	while len(unused_cities) > 0:
		print(i, ": ")
		cluster_list.append(cluster_child(get_start_city(unused_cities), unused_cities, cluster_dict, i))
		i += 1

	return cluster_list

def cluster_child(start_city, unused_cities, cluster_dict, iter):
	pqueue = PriorityQueue()
	for i in range(len(unused_cities)):
		pqueue.put((start_city.costTo(unused_cities[i]), rand(), unused_cities[i]))
	if pqueue.qsize() > 0:
		_, _, next_city = pqueue.get()
		for i in range(len(unused_cities)):
			pqueue.put((next_city.costTo(unused_cities[i]), rand(), unused_cities[i]))
	if pqueue.qsize()>0:
		_, _, next_city = pqueue.get()
		for i in range(len(unused_cities)):
			pqueue.put((next_city.costTo(unused_cities[i]), rand(), unused_cities[i]))
	if pqueue.qsize() > 0:
		_, _, next_city = pqueue.get()
		for i in range(len(unused_cities)):
			pqueue.put((next_city.costTo(unused_cities[i]), rand(), unused_cities[i]))


	child_set = set()
	while len(child_set) < CLUSTER_SIZE and len(child_set) < len(unused_cities):
		_, _, to_add = pqueue.get()
		child_set.add(to_add)

	child_set_cpy = child_set.copy()

	for i in range(len(child_set)):
		city = child_set_cpy.pop()
		unused_cities.remove(city)
		cluster_dict[city] = iter

	child_set_list = set_to_list(child_set.copy())
	print([child._name for child in child_set])
	return set_to_list(child_set)

def find_children_connections(children):
	cluster_connection_matrix = [[(None, None) for i in range(len(children))] for j in range(len(children))]
	cluster_cost_matrix = [[np.inf for i in range(len(children))] for j in range(len(children))]

	child_cnt = len(children)

	if child_cnt == 2:
		cost, conn_1= shortest_connections_for_two(children[0], children[1])
		cost, conn_2= shortest_connections_for_two(children[1], children[0])
		cluster_cost_matrix[0][1] = cost
		cluster_connection_matrix[0][1] = conn_1
		cluster_cost_matrix[1][0] = cost
		cluster_connection_matrix[1][0] = conn_2
	else:
		for i in range(child_cnt):
			for j in range(child_cnt):
				if i == j:
					continue
				cost, conn_1 = shortest_connection(children[i], children[j])
				cluster_cost_matrix[i][j] = cost
				cluster_connection_matrix[i][j] = conn_1

	return cluster_cost_matrix, cluster_connection_matrix

def shortest_connection(city_list1, city_list2):
	prioQueue = PriorityQueue()
	avg = 0

	for city in city_list1:
		for city_to in city_list2:
			curr_cost = city.costTo(city_to)
			avg = avg + curr_cost if curr_cost != np.inf else avg + 500
			conn = (city, city_to)
			prioQueue.put((curr_cost, hash(conn), conn))
	avg = avg /(len(city_list1) * len(city_list2))

	return avg, prioQueue

def shortest_connections_for_two(city_list1, city_list2):
	min_1 = np.inf
	min_2 = np.inf
	conn_1 = None
	conn_2 = None
	prioQueue = PriorityQueue()

	for city in city_list1:
		for city_to in city_list2:
			curr_cost = city.costTo(city_to)
			prioQueue.put((curr_cost, hash((city, city_to)), (city, city_to)))

	# min_1, _, conn_1 = prioQueue.get()
	# min_2, _, conn_2 = prioQueue.get()
	# while(conn_has_overlap(conn_2, conn_1)):
	# 	min_2, _, conn_2 = prioQueue.get()

	return 0, prioQueue

def conn_has_overlap (conn_1, conn_2):
	if conn_2 is None:
		return False
	for city in conn_2:
		for other_city in conn_1:
			if city == other_city:
				return True

	return False

def select_connection_tuple(cluster_route, cluster_conn_matrix):
	used_cities = []
	route_conn = []
	for i in range(len(cluster_route)):
		prev_route_len = len(route_conn)
		curr = cluster_route[i]
		next = cluster_route[0] if i == len(cluster_route)-1 else cluster_route[i+1]
		poss_connections = cluster_conn_matrix[curr][next]
		while prev_route_len == len(route_conn):
			conn = poss_connections.get()[2]
			if conn[0] not in used_cities and conn[1] not in used_cities:
				route_conn.append(conn)
				used_cities.append(conn[0])
				used_cities.append(conn[1])
				break
		print(i, ":", len(route_conn))

	return route_conn

def get_start_city(set):
	for e in set:
		break
	return e

def set_to_list(set):
	set_cpy = set.copy()
	list = []
	while (len(set_cpy) != 0):
		list.append(set_cpy.pop())
	return list

def min_conn(child_idx, cost_matrix, conn_matrix):
	min_row = np.inf
	min_col = np.inf
	min_col_val = None
	min_row_val = None
	for i in range(len(cost_matrix)):
		curr_row = cost_matrix[child_idx][i]
		curr_col = cost_matrix[i][child_idx]
		if curr_row < min_row:
			min_row = curr_row
			min_row_val = conn_matrix[child_idx][i]
			row_y = i
			if conn_matrix[row_y][child_idx] < min_col:
				min_col = conn_matrix[row_y][child_idx]
				min_col_val = conn_matrix[row_y][child_idx]
		elif curr_col < min_col:
			min_col = curr_col
			min_col_val = conn_matrix[i][child_idx]

	return min_row, min_row_val, min_col, min_col_val

def branch_and_bound_algorithm(cities_cnt, cityMatrix, start_c):
	lowerbound = reduce_cost_matrix(cityMatrix)
	my_route = []
	my_route.append(start_c)
	init_city = start_c
	prioQueue = PriorityQueue()
	init_state = State(my_route, cityMatrix, lowerbound)
	prioQueue.put((lowerbound, my_route, init_state))
	waitQueue = PriorityQueue()
	foundTour = False
	pruned_states = 0

	j = 0
	while not foundTour:
		if prioQueue.qsize() < 1:
			print("error")
		lowerbound, curr_path, curr_state = prioQueue.get()
		start_city = curr_path[-1]
		my_route = curr_state.route
		cityMatrix = curr_state.cost_matrix
		lowerbound = curr_state.lowerbound

		for i in range(cities_cnt):
			if i != init_city:
				if cityMatrix[start_city][i] != np.inf:
					child_val, child_matrix = find_child_val(start_city, i, cityMatrix, lowerbound)
					my_route.append(i)
					child_state = State(my_route, child_matrix, child_val)
					waitQueue.put((child_val//len(my_route), my_route.copy(), child_state))
					my_route.pop()
		for i in range(SPACE_ALLOWANCE):
			if waitQueue.qsize() > 0:
				prioQueue.put(waitQueue.get())
		pruned_states += waitQueue.qsize()
		waitQueue.queue.clear()


		# TODO: len(cities)-1?
		if len(my_route) == cities_cnt:
			foundTour = True


	return my_route, pruned_states

def setup_start_and_end(childMatrix, start, end):
	for i in range(len(childMatrix)):
		childMatrix[i][start] = np.inf
		childMatrix[end][i] = np.inf
	childMatrix[start][end] = np.inf

def Kmeans(cities):
	cities_cnt = len(cities)
	kcnt = cities_cnt//CLUSTER_SIZE + 1
	cluster_list = [Cluster() for k in range(kcnt)]
	isUpdating = True
	while isUpdating:
		isUpdating = False
		assign_cities_to_cluster(cities, cluster_list)
		for cluster in cluster_list:
			if len(cluster.cities) < MIN_CLUSTER_SIZE:
				dissolve_cluster(cluster, cluster_list)
				unchanged = False
				continue
			if len(cluster.cities) > MAX_CLUSTER_SIZE:
				split_cluster(cluster, cluster_list)
				unchanged = False
				continue
			unchanged = cluster.update()
			if not unchanged:
				isUpdating = True

	assign_cities_to_cluster(cities, cluster_list)
	return [cluster.cities for cluster in cluster_list]

def assign_cities_to_cluster(cities, cluster_list):
	for city in cities:
		min_cluster = None
		min_val = np.inf
		for cluster in cluster_list:
			dist = cluster.distance(city)
			if dist < min_val:
				min_cluster = cluster
				min_val = dist
		min_cluster.add_city(city)

class Cluster():
	def __init__(self, xy = None):
		self.data_range ={'x':[-1.5, 1.5], 'y':[-1.0, 1.0]}
		if xy is not None:
			self._x = xy[0]
			self._y = xy[1]
			self.loc = None
		else:
			self._x = None
			self._y = None
			self.loc = self.random_assignment()

		self.old_loc = None
		self.cities = []

	def random_assignment(self):
		xr = self.data_range['x']
		yr = self.data_range['y']
		x = random.uniform(0.0, 1.0)
		y = random.uniform(0.0, 1.0)
		if True:
			xval = xr[0] + (xr[1] - xr[0]) * x
			yval = yr[0] + (yr[1] - yr[0]) * y
			self._x = xval
			self._y = yval
			return QPointF(xval,yval)

	def update(self):
		self.old_loc = (self._x, self._y)
		self.loc = self.computeCentroid()
		cost = math.sqrt((self._x - self.old_loc[0]) ** 2 +
						 (self._y - self.old_loc[1]) ** 2)

		tot = int(math.ceil(cost * self.MAP_SCALE))
		return tot == 0

	MAP_SCALE = 1000.0
	def distance(self, other_city):
		# Euclidean Distance
		cost = math.sqrt((other_city._x - self._x) ** 2 +
						 (other_city._y - self._y) ** 2)

		return int(math.ceil(cost * self.MAP_SCALE))

	def computeCentroid(self):
		if len(self.cities) == 0:
			return self.loc
		yval = 0
		xval = 0
		for city in self.cities:
			yval += city._y
			xval += city._x
		yval/=len(self.cities)
		xval/=len(self.cities)
		self._x = xval
		self._y = yval
		self.cities.clear()
		return QPointF(xval, yval)

	def clearCities(self):
		self.cities.clear()
	def add_city(self, city):
		self.cities.append(city)
	def change_loc(self, xy):
		self._x = xy[0]
		self._y = xy[1]

def dissolve_cluster(cluster, cluster_list):
	cluster_list.remove(cluster)
	assign_cities_to_cluster(cluster.cities, cluster_list)

def split_cluster(cluster, cluster_list):
	std_dev_x = 0
	std_dev_y = 0
	for city in cluster.cities:
		std_dev_x += abs(cluster._x - city._x)
		std_dev_y += abs(cluster._y - city._y)

	std_dev_x/= len(cluster.cities)
	std_dev_y/= len(cluster.cities)

	split_x = cluster._x + std_dev_x
	split_y = cluster._y + std_dev_y
	other_x = cluster._x - std_dev_x
	other_y = cluster._y - std_dev_y

	new_cluster = Cluster((split_x, split_y))
	cluster.change_loc((other_x, other_y))
	cluster_list.append(new_cluster)
	cluster.clearCities()




